# Template config of Kaori

template:
  mail:
    registration:
      file: "template/email/registrazione.txt"
      object: "CONFERMA REGISTRAZIONE"
  music:
    name: "template/music/name.tmpl"
  html:
    redirect: "template/html/redirect.html"